### ISSUE TITLE
First Draft: MVP Content

### ISSUE THREAD

**Issue by ashes999** [deengames-prototypes/a-day-and-a-night-v3#3]
**Finish fast,** or we're not going to make it.
# MVP
- [x] Write more codez. Eh, @Wulf ?
  - [x] Show deeds total in menu item: `x good, y bad`
  - [x] Menu item to see details of deeds
- [x] Pick content to form MVP from #1. This includes at least one arc of deeds, and some achievements.
  - [x] Intro mentions killing 100 people
  - [x] Rework text to add more self-exhortation to good in the protagonist's messages, and to add appropriate responses. He was an uber warrior, trying to be good, may relapse occasionally.
  - [x] Deeds
    - [x] 5x/day salah
    - [x] Random grave worship
    - [x] Kid drowning in a pond
    - [x] Shaykh giving halaqah
    - [x] Series of greyscale flashbacks. Figure out triggers. Include tawbah and istighfaar (actions of repentance)
      - [x] Themed with the hadith of killing 99 + 1 people. Kills the 100th ... (mentions he is the Kings Blade)
      - [x] Next flashback (trigger is tell the shaykh you're busy): asks the 'aalim. He killed those people under orders. Reply is "..."
      - [x] Next flashback: He ran away because he has a conscience, to right his wrongs. Go to x town. Hastily.
      - [x] Having achieved all these in-game, you get an achievement.
    - [x] Monster arc
    - [x] Magician's arc
    - [x] Tahajjud in your room
    - [x] Tadabbur at the mountaintop
    - [x] Ore and blacksmith quest. He makes an axe capable of smashing statues ...
    - [x] Screw up the forge
    - [x] Idols in the masjid. (Can throw money to them, can break them, confront samiri, plant the axe)
    - [x] Fall/jump off the cliff and die
    - [x] Random acts of evil (brainstorm and implement at least six)
      - [x] Kill yourself (+badge)
      - [x] Start in the top floor of the inn. You can leave without paying.
      - [x] Inn: you can take stuff from other peoples rooms (stealing!)
      - [x] Entertain discussion with a backbiter/nameemah lady
      - [x] Alcohol store. Buy it and drink it.
      - [x] Alcohol store: buy it and dump it
  - [x] Achievements
    - [x] First sin
    - [x] Nafsun Lawwaamah: good/bad/good/bad deeds in that order
    - [x] Ibrahim Alayhi Salaam (break idols except the chief, and plant the axe on him)
    - [x] Self Destruct (magician's quest)
    - [x] Qalbun mu'allaqtun lil masjid (pray 5x in the masjid)
    - [x] Shaheed (drown in pond)
    - [x] You Monster!
    - [x] Pet-Friendly (anti-poachers)
    - [x] Seeker of Knowledge (talk to shaykh 3x)
    - [x] Discover your identity
    - [x] Killing yourself forever (suicide)
    - [x] Thief badge (steal a lot)
- [x] Ending: Execution is because he is seen as a traitor to the king, who's firawn. (Pharoah made him do bad things -- to Bani-Israeel-likes, who are slaves.)
- [x] Wrap it up
  - [x] Logging of interesting things
  - [x] Time passes during battles
  - [x] Tweak the difficulty of the monster arc (XP required to win), including skills (what and how strong and how expensive)
  - [x] Play through and see how long it takes to do everything
  - [x] If necessary, replay and tweak the time speed until it's about right, or shorten the day.
  - [x] Get Saif's feedback on it. Decide to fix and ship it, or dump it.
- [x] Needs more work.
  - [x] Redo cave event so that it doesn't break if we change the map
  - [x] Potion maker house (external)
  - [x] Potion maker makes potions out of monster-drop ingredients
    - [x] Bundle of herbs
    - [x] Tea
    - [x] Anti-sleep accessory
  - [x] Swap above two items for two or more potions
    - [x] Full heal potion
    - [x] Next battle strength up
  - [x] Potion maker quests
    - [x] Scorpion blocks the cave
    - [x] If you ask the potion lady about monsters, she'll refer you to the accessory
    - [x] With it, you can scurry away the scorpion at the cave entrance
    - [x] Quest to save a kids life who was stung by the scorpion
      - [x] There's some kid in bed, she's tried some potions but now it's down to the last one (needs ingredients)
      - [x] He dies if not found and healed after a number of hours
      - [x] You need a bunch of ingredients from various sources for the cure
      - [x] He's okay if cured, sleeping peacefully
      - [x] Achievement (swap out thief one)
  - [x] Option to rest at the inn
  - [x] Can escape from battles
  - [x] Level up should heal you
  - [x] Lengthen game time
  - [x] Pre-drowning warning
  - [x] Middle and near-end day warnings
  - [x] Intro: make it obvious you're playing against the clock.

**Comment by Wulf** [comment]
Ashes, can we remove the 'Simple Mouse System' requirement for the Achievements page?

**Comment by Wulf** [comment]
![image](https://cloud.githubusercontent.com/assets/4259838/15637027/4476ed7e-25d5-11e6-87c7-5b775a67d615.png)

The keyboard works :)

**Comment by Wulf** [comment]
Also, when an achievement is "locked", the description doesn't show, and the opacity is halved. When it is unlocked, I made it max opacity and it also shows the description.

**Comment by ashes999** [comment]
Done. Looks excellent, mashaAllah. How did you reverse-engineer the achievements so fast? (Please open a PR with your changes.)

**Comment by ashes999** [comment]
Hmm, is it relatively easy to grey-out locked achievements?

**Comment by Wulf** [comment]
Yeah, just use photoshop to grayscale the image, and have some sort of file name scheme; i.e. `original.png` & `original_grayscale.png`

Show one over the other when locked/unlocked.

I'm finding it difficult to do a pull-request through command line. Guidance?

**Comment by Wulf** [comment]
I could just use the web-interface I guess, but it'd be more fun to learn the other way.

**Comment by Wulf** [comment]
Okay, I'll fork it and pull-request from the interface then.

**Comment by ashes999** [comment]
Pull Requests exist on GitHub, not git. There's no command-line for it.

I assume you either forked or used a different branch. If not, forget it, just merge/push and I'll review it later.

**Comment by Wulf** [comment]
Next time, I'll create a feature branch. 

Next up for me:

```
    Show deeds total in menu item: x good, y bad
    Menu item to see details of deeds
```

I saw the map and the events along the edge of the cliff. Are you allowed to suicide in this game lol? Also, I want to bring something up regarding good/bad deeds later.

**Comment by ashes999** [comment]
Fire away (with regards to whatever you want to bring up).

Suicide, eh, I never thought of that. Sure, we can integrate that. One thing we need is MOAR ways to die in the game.

**Comment by ashes999** [comment]
Pending changes merged. Approved by @silatsaif !
